name: build

on:
  push:
    branches:
      - master
jobs:
  build-win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        curl -L https://github.com/iwalton3/mpv-winbuild-cmake/releases/download/v20230304-git-362256e/mpv-dev-x86_64-20230304-git-362256e.7z > mpv.7z
        7z x mpv.7z
        mv libmpv-2.dll mpv-2.dll
        pip install wheel
        pip install git+https://github.com/pythonnet/pythonnet@438bcdd3f0b2e2ee358b407cfc96e4385e5783fc
        pip install .[all] pywebview==3.4 pywin32==304
        ./regen_pot.sh
        ./gen_pkg.sh --skip-build
        python ./get_pywebview_natives.py
      shell: bash
    - name: PyInstaller Bootloader
      run: |
        ./gen_pkg.sh --get-pyinstaller; cd pyinstaller/bootloader; python ./waf distclean all; cd ..; pip install .
      shell: bash
    - name: Main Build
      run: |
        .\build-win.bat
      shell: cmd
    - name: Artifact Rename
      run: |
        ./artifacts.sh standard
      shell: bash
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ${{ github.workspace }}/publish/Installer/*.exe
